### ISSUE TITLE
404 Not found on npm

### ISSUE THREAD

**Issue by klase** [newrelic/node-newrelic-superagent#2]
I get "npm ERR! 404 Not Found: @newrelic/superagent@latest" when doing "npm install @newrelic/superagent"

**Comment by NatalieWolfe** [comment]
Hi Klase! We haven't published this module because we haven't had a customer available to test it yet. If you would be willing to give it a quick test then we can publish this. Testing it would just involve installing the module from the github repository and testing your application to make sure that no functionality broke as a last-step sanity check.

We have done extensive internal testing, but we like to get at least one real-world use case tested before publishing modules.

To install this module from the repository, put this into your package.json dependencies:
```json
  "dependencies": {
    "@newrelic/superagent": "git+ssh://git@github.com:newrelic/node-newrelic-superagent.git"
  }
```

**Comment by klase** [comment]
Hi! 

We've installed the module but not getting any metrics from our xhr calls with superagent. Are there additional steps to get this to work than just requiring the library as per the readme? We're using superagent 3.8.2.

Thanks

**Comment by NatalieWolfe** [comment]
Do you also have the [New Relic Agent](https://www.npmjs.com/package/newrelic) installed? And when you say "xhr calls," are you using this module in the browser or in a server-side Node application?

**Comment by klase** [comment]
Yes, the node agent is installed and working but any xhr calls we do (from the node server) comes up as anonymous middleware, so we've used newrelic.startSegment to manually measure these for now.

**Comment by NatalieWolfe** [comment]
Hmm, that sounds like a more than can be debugged through a GH issue. Would you mind submitting your query to support? https://support.newrelic.com/

If you create a post on our community forum and then send the link here, I'll make sure it gets attention from our technical support engineers.

**Comment by klase** [comment]
ok thanks

**Comment by jpd4ag** [comment]
Any idea where this has gotten to?

We been using this for a while now and would like to see it be added to the public registry.

It seems to be working fine for us and we have provide feedback, are there any known issues holding this up?

**Comment by NatalieWolfe** [comment]
Sorry, should have closed this ticket sooner. The module was published three weeks ago to npm (https://www.npmjs.com/package/@newrelic/superagent). Our next release of the `newrelic` module will incorporate it built in to the agent.

Closing this ticket now since it was published, thus resolving the 404 issue.

**Comment by NatalieWolfe** [comment]
[New Relic Node Agen v4.9.0](https://www.npmjs.com/package/newrelic) is now published. It has the superagent instrumentation integrated, so you should not need to install the `@newrelic/superagent` module directly anymore.
