### ISSUE TITLE
Shipping large amounts of redundant files

### ISSUE THREAD

**Issue by SimonSchick** [newrelic/node-newrelic-superagent#4]
As a general note: Most of your npm packages (including newlic, @newrelic/koa, @newrelic/native-metrics) appear to be rather large and seem to be shipping many redundant files such as tests, source files or even vendored dependencies.

As for the superagent package:

The following files should probably not be shipped:

```
.eslintignore
.eslintrc
.travis.yml
CHANGELOG.md
newrelic_agent.log
tests
```

Please note that `newrelic_agent.log` is 14 **megabytes** and seems to contain build log data, I have not yet looked into the kind of log data in there but it certainly shouldn't be on npm.

Please look into using the `files` property in `package.json` to reduce package bloat.

**Comment by NatalieWolfe** [comment]
Thanks for letting us know. We noticed this recently as well and have started updating the `.npmignore` files to exclude more. Unfortunately the instrumentation modules (`@newrelic/koa` and `@newrelic/superagent`) must include their tests in the packages so that the agent module can run them again itself. We accidentally also included the `tests/versioned/node_modules` directory as well and that is a large amount of the bloat too.

**Comment by SimonSchick** [comment]
I appreciate you looking into this!
As mentioned using `.npmignore` has become somewhat of an anti pattern as most people will keep accidentally publishing files that their consumer don't need, you might want to migrate entirely to `files` as described above :)

**Comment by NatalieWolfe** [comment]
Unfortunately using `files` alone would include the `tests/versioned/node_modules` directory as well, which we obviously don't want. Since we have to use `.npmignore` to exclude that directory and I'd rather have a single point for determining package contents, I think going with `.npmignore` the whole way is better for our use case.

**Comment by SimonSchick** [comment]
The alternative is that you _invert_ the `.npmignore` by starting it with `/*` and then mark each folder you want via `!...`, maybe that would help :)

Anyways, thanks for looking into this, I appreciate it!

**Comment by SimonSchick** [comment]
Hey @NatalieWolfe just to clarify (since issues are sadly disabled on the other repos), are you going to perform the same cleanups on the other packages too? :)
